# Generated by Django 6.0.2 on 2026-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_client_domain_remove_client_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='domain',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
