# Generated by Django 6.0.2 on 2026-03-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image_supplier_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
